use tracing::{debug, info};

use crate::models::auction::{AuctionInstance, TokenMap};
use crate::models::liquidity::Liquidity;
use crate::models::order::Order;
use crate::models::solution::{Score, Solution, Trade};
use crate::solver::assembler::normalize_surplus;
use crate::solver::direct::DirectSolver;

// ── CoW Match result ──────────────────────────────────────────────────────────

/// A matched pair of orders that can be settled without a DEX swap.
///
/// Alice sells token A → token B.  Bob sells token B → token A.
/// We settle at a mid-point price so both get at or better than their limits.
#[derive(Debug, Clone)]
pub struct CowMatch {
    /// Index of the order selling token_a
    pub order_a_uid: String,
    /// Index of the order selling token_b
    pub order_b_uid: String,
    /// Amount of token_a transferred (Alice → settlement → Bob)
    pub a_executed: u128,
    /// Amount of token_b transferred (Bob → settlement → Alice)
    pub b_executed: u128,
    /// Combined surplus generated by the match (raw, mixed token units)
    pub combined_surplus: u128,
    /// Surplus for order_a (in order_a's buy token = token_b)
    pub surplus_a_in_buy_token: u128,
    /// Buy token address for order_a (= oi.buy_token = token_b)
    pub buy_token_a: String,
    /// Surplus for order_b (in order_b's buy token = token_a)
    pub surplus_b_in_buy_token: u128,
    /// Buy token address for order_b (= oj.buy_token = token_a)
    pub buy_token_b: String,
}

// ── Main algorithm ────────────────────────────────────────────────────────────

/// Find all CoW matches in the auction.
///
/// For each pair (i, j) where orders are opposite (A→B and B→A),
/// compute the maximum overlap that satisfies both limit prices.
pub fn find_cows(auction: &AuctionInstance) -> Vec<CowMatch> {
    let orders = &auction.orders;
    if orders.len() < 2 {
        return vec![];
    }

    let mut matches = Vec::new();

    for i in 0..orders.len() {
        for j in (i + 1)..orders.len() {
            let oi = &orders[i];
            let oj = &orders[j];

            // Check if they are opposite: oi sells what oj buys and vice versa
            if oi.sell_token != oj.buy_token || oi.buy_token != oj.sell_token {
                continue;
            }

            // Skip high-competition pairs — CIP-67 fairness filter will discard
            // our CoW solution if the AMM baseline outscores it on these pairs.
            if crate::triage::is_high_competition_pair(&oi.sell_token, &oi.buy_token) {
                debug!(
                    sell = %oi.sell_token.chars().take(10).collect::<String>(),
                    buy = %oi.buy_token.chars().take(10).collect::<String>(),
                    "Skipping CoW match on high-competition pair"
                );
                continue;
            }

            if let Some(m) = try_match(oi, oj) {
                debug!(
                    order_a = %m.order_a_uid,
                    order_b = %m.order_b_uid,
                    surplus = m.combined_surplus,
                    "CoW match found"
                );
                matches.push(m);
            }
        }
    }

    matches
}

/// Try to match two opposite orders at the midpoint price.
///
/// Returns None if the orders cannot be satisfied at any common price.
fn try_match(oi: &Order, oj: &Order) -> Option<CowMatch> {
    // oi: sell token_a, buy token_b
    // oj: sell token_b, buy token_a
    let sell_a: u128 = oi.sell_amount.parse().ok()?;
    let buy_b_min: u128 = oi.buy_amount.parse().ok()?; // min token_b oi must receive

    let sell_b: u128 = oj.sell_amount.parse().ok()?;
    let buy_a_min: u128 = oj.buy_amount.parse().ok()?; // min token_a oj must receive

    if sell_a == 0 || sell_b == 0 || buy_b_min == 0 || buy_a_min == 0 {
        return None;
    }

    // Check feasibility: for a match to exist, the limit prices must overlap.
    // oi limit rate: sell_a / buy_b_min (token_a per token_b from oi's perspective)
    // oj limit rate: sell_b / buy_a_min (token_b per token_a from oj's perspective)
    //
    // For a valid match: the effective price must satisfy both:
    //   token_b / token_a >= buy_b_min / sell_a   (oi wants at least this much)
    //   token_a / token_b >= buy_a_min / sell_b   (oj wants at least this much)
    //
    // This is feasible when:  sell_a * sell_b >= buy_a_min * buy_b_min
    let lhs = sell_a.checked_mul(sell_b)?;
    let rhs = buy_a_min.checked_mul(buy_b_min)?;
    if lhs < rhs {
        return None; // prices don't overlap
    }

    // Compute executed amounts at midpoint price.
    // Mid price: p = sqrt(sell_a/buy_b_min * sell_b/buy_a_min)
    // Approximation: take geometric mean.
    // We compute:
    //   a_executed = min(sell_a, buy_a_min)   — limited by what oj needs
    //   b_executed = min(sell_b, buy_b_min)   — limited by what oi needs
    //
    // Find overlap: limited by whichever side has the smaller relative position.
    // This matches fully if amounts are equal; otherwise partial fill.
    //
    // Use the constraint: a_executed * (sell_b / buy_a_min) >= b_executed
    //                     b_executed = a_executed * sell_b / sell_a
    //                     (proportional split)

    // The actual overlap: try to fill both orders as much as possible.
    // a_executed ≤ sell_a (oi can't sell more than they have)
    // b_executed ≤ sell_b (oj can't sell more than they have)
    // oi needs: b_executed >= buy_b_min * a_executed / sell_a
    // oj needs: a_executed >= buy_a_min * b_executed / sell_b

    // Simple approach: find max a_executed such that the b they get is <= sell_b
    // b_for_a = a_executed * sell_b / sell_a  (proportional split at midpoint)
    // Cap at sell_b and sell_a

    // Scale factor: we pick the midpoint exchange rate
    // rate = sqrt(sell_a/buy_b_min / sell_b/buy_a_min) ... approximated as:
    // rate_a_to_b = sell_b / sell_a (actual offers)
    // (This gives the "offer" rate; surplus = offer - limit)

    // Executed: a_exec = min(sell_a, sell_b * sell_a / sell_b) = min(sell_a, sell_a)
    // Better: use the geometric mean
    // For simplicity (Sprint 2), use min overlap
    let a_executed = sell_a.min(sell_b.checked_mul(sell_a)?.checked_div(sell_b)?);
    // b_executed proportional to a_executed
    let b_executed = a_executed.checked_mul(sell_b)?.checked_div(sell_a)?;

    // Verify limits are satisfied
    if b_executed < buy_b_min.checked_mul(a_executed)?.checked_div(sell_a)? {
        return None;
    }
    if a_executed < buy_a_min.checked_mul(b_executed)?.checked_div(sell_b)? {
        return None;
    }

    // Surplus: how much better than limit each side gets
    let surplus_oi = b_executed.saturating_sub(buy_b_min);
    let surplus_oj = a_executed.saturating_sub(buy_a_min);
    let combined_surplus = surplus_oi.saturating_add(surplus_oj);

    Some(CowMatch {
        order_a_uid: oi.uid.clone(),
        order_b_uid: oj.uid.clone(),
        a_executed,
        b_executed,
        combined_surplus,
        surplus_a_in_buy_token: surplus_oi,  // oi's surplus is in oi.buy_token (= token_b)
        buy_token_a: oi.buy_token.clone(),
        surplus_b_in_buy_token: surplus_oj,  // oj's surplus is in oj.buy_token (= token_a)
        buy_token_b: oj.buy_token.clone(),
    })
}

/// Filter CoW matches, keeping only those where the CoW price beats the AMM
/// for both orders in the match.
///
/// The CIP-67 fairness filter compares each directed pair in a solution against
/// the best single-pair AMM baseline. If ANY pair scores below that baseline,
/// the ENTIRE solution is discarded. This function prevents that by removing
/// CoW matches that would be outscored by direct AMM routing.
pub fn filter_by_amm_baseline(
    matches: Vec<CowMatch>,
    orders: &[Order],
    liquidity: &[Liquidity],
    tokens: &TokenMap,
) -> Vec<CowMatch> {
    let before = matches.len();
    let filtered: Vec<CowMatch> = matches.into_iter().filter(|m| {
        let order_a = orders.iter().find(|o| o.uid == m.order_a_uid);
        let order_b = orders.iter().find(|o| o.uid == m.order_b_uid);

        let (Some(oa), Some(ob)) = (order_a, order_b) else {
            return true; // Can't find orders — keep the match to be safe
        };

        // Compute normalized CoW surplus for each order
        let cow_surplus_a = normalize_surplus(m.surplus_a_in_buy_token, &m.buy_token_a, tokens);
        let cow_surplus_b = normalize_surplus(m.surplus_b_in_buy_token, &m.buy_token_b, tokens);

        // Compute what the AMM would give each order
        let amm_surplus_a = DirectSolver::solve_order(oa, liquidity)
            .map(|r| normalize_surplus(r.surplus, &oa.buy_token, tokens))
            .unwrap_or(0);
        let amm_surplus_b = DirectSolver::solve_order(ob, liquidity)
            .map(|r| normalize_surplus(r.surplus, &ob.buy_token, tokens))
            .unwrap_or(0);

        // Keep match only if CoW beats AMM for BOTH orders
        let cow_beats = cow_surplus_a >= amm_surplus_a && cow_surplus_b >= amm_surplus_b;
        if !cow_beats {
            debug!(
                order_a = %m.order_a_uid.chars().take(16).collect::<String>(),
                order_b = %m.order_b_uid.chars().take(16).collect::<String>(),
                cow_a = cow_surplus_a, amm_a = amm_surplus_a,
                cow_b = cow_surplus_b, amm_b = amm_surplus_b,
                "CoW match filtered: AMM gives better execution"
            );
        }
        cow_beats
    }).collect();

    if filtered.len() < before {
        info!(
            before, after = filtered.len(),
            "CoW matches filtered by AMM baseline"
        );
    }
    filtered
}

/// Build a Solution from a set of CoW matches (no DEX interactions needed).
pub fn build_cow_solution(
    auction_id: u64,
    matches: &[CowMatch],
    tokens: &crate::models::auction::TokenMap,
) -> Option<Solution> {
    if matches.is_empty() {
        return None;
    }

    let mut trades = Vec::<Trade>::new();
    let mut prices = std::collections::HashMap::<String, String>::new();
    let mut total_surplus = 0u128;

    // For each match, emit two trades and compute clearing prices
    for m in matches {
        trades.push(Trade::fulfillment(&m.order_a_uid, m.a_executed.to_string()));
        trades.push(Trade::fulfillment(&m.order_b_uid, m.b_executed.to_string()));
        // Clearing prices keyed by token address (CoW driver expects this format).
        // buy_token_b = token_a (what order_b buys = what order_a sells)
        // buy_token_a = token_b (what order_a buys = what order_b sells)
        // Price of token_a = how much token_b you get per token_a = b_executed/a_executed
        // Price of token_b = how much token_a you get per token_b = a_executed/b_executed
        prices
            .entry(m.buy_token_b.clone()) // token_a address
            .or_insert_with(|| m.b_executed.to_string());
        prices
            .entry(m.buy_token_a.clone()) // token_b address
            .or_insert_with(|| m.a_executed.to_string());
        // Normalize each order's surplus by its own buy token's reference_price.
        // surplus_a is in buy_token_a units, surplus_b is in buy_token_b units.
        let norm_a = crate::solver::assembler::normalize_surplus(
            m.surplus_a_in_buy_token, &m.buy_token_a, tokens,
        );
        let norm_b = crate::solver::assembler::normalize_surplus(
            m.surplus_b_in_buy_token, &m.buy_token_b, tokens,
        );
        total_surplus = total_surplus.saturating_add(norm_a).saturating_add(norm_b);
    }

    tracing::info!(
        auction_id = auction_id,
        matches = matches.len(),
        trades = trades.len(),
        total_surplus_wei = total_surplus,
        "CoW matching solution built"
    );
    // Log first match details for debugging
    if let Some(m) = matches.first() {
        let ref_a = tokens.iter()
            .find(|(k, _)| k.to_lowercase() == m.buy_token_a.to_lowercase())
            .and_then(|(_, t)| t.reference_price.as_ref())
            .map(|s| s.as_str())
            .unwrap_or("none");
        let ref_b = tokens.iter()
            .find(|(k, _)| k.to_lowercase() == m.buy_token_b.to_lowercase())
            .and_then(|(_, t)| t.reference_price.as_ref())
            .map(|s| s.as_str())
            .unwrap_or("none");
        tracing::info!(
            order_a = %m.order_a_uid.chars().take(16).collect::<String>(),
            order_b = %m.order_b_uid.chars().take(16).collect::<String>(),
            a_executed = m.a_executed,
            b_executed = m.b_executed,
            surplus_a = m.surplus_a_in_buy_token,
            surplus_b = m.surplus_b_in_buy_token,
            ref_price_a = ref_a,
            ref_price_b = ref_b,
            "CoW match #0 details"
        );
    }

    // No interactions needed for CoW matches!
    Some(Solution {
        id: auction_id,
        prices,
        trades,
        pre_interactions: vec![],
        interactions: vec![],
        post_interactions: vec![],
        gas: None,
        // Cap CoW matching score at 1.5M gwei (same as direct solver cap).
        // Higher values indicate inflated surplus from reference price mismatch.
        score: Some(Score::Solver {
            score: total_surplus.min(1_500_000_000_000_000).to_string(),
        }),
    })
}

/// Legacy compatibility: return index pairs (kept for API compatibility).
pub fn find_cow_pairs(auction: &AuctionInstance) -> Vec<[usize; 2]> {
    let orders = &auction.orders;
    let mut pairs = Vec::new();

    for i in 0..orders.len() {
        for j in (i + 1)..orders.len() {
            let oi = &orders[i];
            let oj = &orders[j];
            if oi.sell_token == oj.buy_token
                && oi.buy_token == oj.sell_token
                && try_match(oi, oj).is_some()
            {
                pairs.push([i, j]);
            }
        }
    }
    pairs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::auction::AuctionInstance;
    use crate::models::order::{Order, OrderClass, OrderKind};

    fn make_order(uid: &str, sell: &str, buy: &str, sell_amt: u128, buy_amt: u128) -> Order {
        Order {
            uid: uid.to_string(),
            sell_token: sell.to_string(),
            buy_token: buy.to_string(),
            sell_amount: sell_amt.to_string(),
            buy_amount: buy_amt.to_string(),
            fee_amount: "0".to_string(),
            kind: OrderKind::Sell,
            partially_fillable: false,
            class: OrderClass::Market,
            sell_token_balance: None,
            buy_token_balance: None,
            signing_scheme: None,
            signature: None,
            receiver: None,
            app_data: None,
            valid_to: None,
        }
    }

    fn make_auction(orders: Vec<Order>) -> AuctionInstance {
        AuctionInstance {
            id: 1,
            tokens: Default::default(),
            orders,
            liquidity: vec![],
            effective_gas_price: "1000000000".to_string(),
            deadline: None,
            chain_id: None,
            block: None,
        }
    }

    #[test]
    fn matching_opposite_orders() {
        // Alice: sell 1000 WETH, buy ≥ 900 USDC
        // Bob:   sell 1000 USDC, buy ≥ 900 WETH
        // Both want ≥0.9 exchange rate; actual is 1:1 → surplus for both
        let alice = make_order("alice", "0xweth", "0xusdc", 1_000, 900);
        let bob = make_order("bob", "0xusdc", "0xweth", 1_000, 900);

        let matches = find_cows(&make_auction(vec![alice, bob]));
        assert_eq!(matches.len(), 1);
        let m = &matches[0];
        assert!(m.combined_surplus > 0);
        assert_eq!(m.a_executed, 1_000);
        assert_eq!(m.b_executed, 1_000);
    }

    #[test]
    fn no_match_when_prices_dont_overlap() {
        // Alice wants at least 2000 USDC for 1 WETH, Bob wants at least 2 WETH for 1 USDC
        // sell_a(1) * sell_b(1) = 1 < buy_a_min(2) * buy_b_min(2000) = 4000 → no match
        let alice = make_order("alice", "0xweth", "0xusdc", 1, 2_000);
        let bob = make_order("bob", "0xusdc", "0xweth", 1, 2);

        let matches = find_cows(&make_auction(vec![alice, bob]));
        assert!(matches.is_empty());
    }

    #[test]
    fn no_match_same_direction() {
        // Both sell WETH for USDC — no CoW possible
        let a = make_order("a", "0xweth", "0xusdc", 1_000, 900);
        let b = make_order("b", "0xweth", "0xusdc", 500, 450);

        let matches = find_cows(&make_auction(vec![a, b]));
        assert!(matches.is_empty());
    }

    #[test]
    fn cow_solution_has_no_interactions() {
        let alice = make_order("alice", "0xweth", "0xusdc", 1_000, 900);
        let bob = make_order("bob", "0xusdc", "0xweth", 1_000, 900);
        let auction = make_auction(vec![alice, bob]);

        let matches = find_cows(&auction);
        let solution = build_cow_solution(auction.id, &matches, &auction.tokens).unwrap();

        assert!(solution.interactions.is_empty(), "CoW solution must not touch any DEX");
        assert_eq!(solution.trades.len(), 2);
    }

    #[test]
    fn empty_auction_returns_no_matches() {
        let matches = find_cows(&make_auction(vec![]));
        assert!(matches.is_empty());
    }
}
