//! Strategy Attribution (C.3)
//!
//! Decision-level tracking: know which strategy generated, which survived
//! simulation, which was submitted, which won, and which actually monetized.
//!
//! ## Attribution Chain
//!
//! ```text
//! Strategy generated candidate
//!     → Simulation passed/failed
//!         → Submission policy: submit/hold/replace
//!             → Driver accepted/rejected
//!                 → Settlement: won/lost
//!                     → Accounting: predicted vs realized P&L
//! ```

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;
use std::collections::HashMap;

use tracing::debug;

// ── Attribution Record ──────────────────────────────────────────────────────

/// Full attribution record for a single candidate solution.
#[derive(Debug, Clone)]
pub struct AttributionRecord {
    pub auction_id: String,
    /// Which strategy generated this candidate
    pub strategy: String,
    /// Stage this candidate reached
    pub stage: AttributionStage,
    /// Score at generation time (wei)
    pub score_wei: String,
    /// Whether it was the winning submission
    pub was_submitted: bool,
}

/// How far a candidate got in the pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum AttributionStage {
    /// Generated by strategy
    Generated,
    /// Passed simulation
    SimPassed,
    /// Failed simulation
    SimFailed,
    /// Passed submission policy
    PolicyApproved,
    /// Rejected by submission policy
    PolicyRejected,
    /// Actually submitted to the driver
    Submitted,
    /// Won the auction
    Won,
}

impl AttributionStage {
    pub fn as_str(&self) -> &'static str {
        match self {
            AttributionStage::Generated => "generated",
            AttributionStage::SimPassed => "sim_passed",
            AttributionStage::SimFailed => "sim_failed",
            AttributionStage::PolicyApproved => "policy_approved",
            AttributionStage::PolicyRejected => "policy_rejected",
            AttributionStage::Submitted => "submitted",
            AttributionStage::Won => "won",
        }
    }
}

// ── Attribution Tracker ─────────────────────────────────────────────────────

/// Per-strategy attribution counters.
pub struct StrategyAttribution {
    pub generated: AtomicU64,
    pub sim_passed: AtomicU64,
    pub sim_failed: AtomicU64,
    pub policy_approved: AtomicU64,
    pub policy_rejected: AtomicU64,
    pub submitted: AtomicU64,
    pub won: AtomicU64,
}

impl StrategyAttribution {
    fn new() -> Self {
        Self {
            generated: AtomicU64::new(0),
            sim_passed: AtomicU64::new(0),
            sim_failed: AtomicU64::new(0),
            policy_approved: AtomicU64::new(0),
            policy_rejected: AtomicU64::new(0),
            submitted: AtomicU64::new(0),
            won: AtomicU64::new(0),
        }
    }

    fn record(&self, stage: AttributionStage) {
        match stage {
            AttributionStage::Generated => self.generated.fetch_add(1, Ordering::Relaxed),
            AttributionStage::SimPassed => self.sim_passed.fetch_add(1, Ordering::Relaxed),
            AttributionStage::SimFailed => self.sim_failed.fetch_add(1, Ordering::Relaxed),
            AttributionStage::PolicyApproved => self.policy_approved.fetch_add(1, Ordering::Relaxed),
            AttributionStage::PolicyRejected => self.policy_rejected.fetch_add(1, Ordering::Relaxed),
            AttributionStage::Submitted => self.submitted.fetch_add(1, Ordering::Relaxed),
            AttributionStage::Won => self.won.fetch_add(1, Ordering::Relaxed),
        };
    }

    /// Snapshot for metrics/reporting.
    pub fn snapshot(&self) -> AttributionSnapshot {
        AttributionSnapshot {
            generated: self.generated.load(Ordering::Relaxed),
            sim_passed: self.sim_passed.load(Ordering::Relaxed),
            sim_failed: self.sim_failed.load(Ordering::Relaxed),
            policy_approved: self.policy_approved.load(Ordering::Relaxed),
            policy_rejected: self.policy_rejected.load(Ordering::Relaxed),
            submitted: self.submitted.load(Ordering::Relaxed),
            won: self.won.load(Ordering::Relaxed),
        }
    }
}

#[derive(Debug, Clone)]
pub struct AttributionSnapshot {
    pub generated: u64,
    pub sim_passed: u64,
    pub sim_failed: u64,
    pub policy_approved: u64,
    pub policy_rejected: u64,
    pub submitted: u64,
    pub won: u64,
}

impl AttributionSnapshot {
    /// Conversion rate from generated to submitted.
    pub fn submit_rate(&self) -> f64 {
        if self.generated == 0 { 0.0 } else { self.submitted as f64 / self.generated as f64 }
    }

    /// Conversion rate from submitted to won.
    pub fn win_rate(&self) -> f64 {
        if self.submitted == 0 { 0.0 } else { self.won as f64 / self.submitted as f64 }
    }

    /// Simulation pass rate.
    pub fn sim_pass_rate(&self) -> f64 {
        let total_sim = self.sim_passed + self.sim_failed;
        if total_sim == 0 { 0.0 } else { self.sim_passed as f64 / total_sim as f64 }
    }
}

// ── Global Attribution Store ────────────────────────────────────────────────

/// The known strategies in our pipeline.
const STRATEGIES: &[&str] = &[
    "cow", "direct", "combined", "multihop",
    "graph", "split", "external", "fallback",
];

struct AttributionStore {
    strategies: HashMap<String, StrategyAttribution>,
}

impl AttributionStore {
    fn new() -> Self {
        let mut strategies = HashMap::new();
        for &name in STRATEGIES {
            strategies.insert(name.to_string(), StrategyAttribution::new());
        }
        Self { strategies }
    }

    fn record(&self, strategy: &str, stage: AttributionStage) {
        if let Some(attr) = self.strategies.get(strategy) {
            attr.record(stage);
        }
        // Unknown strategies silently ignored
    }

    fn snapshot(&self, strategy: &str) -> Option<AttributionSnapshot> {
        self.strategies.get(strategy).map(|a| a.snapshot())
    }
}

static STORE: OnceLock<AttributionStore> = OnceLock::new();

fn store() -> &'static AttributionStore {
    STORE.get_or_init(AttributionStore::new)
}

// ── Public API ──────────────────────────────────────────────────────────────

/// Record that a strategy reached a specific stage in the pipeline.
pub fn record(strategy: &str, stage: AttributionStage) {
    store().record(strategy, stage);
    debug!(strategy, stage = stage.as_str(), "Attribution recorded");
}

/// Record a full attribution record (for replay/logging).
pub fn record_full(record: &AttributionRecord) {
    store().record(&record.strategy, record.stage);
}

/// Get a snapshot of attribution data for a specific strategy.
pub fn snapshot(strategy: &str) -> Option<AttributionSnapshot> {
    store().snapshot(strategy)
}

/// Get snapshots for all strategies (for Prometheus output).
pub fn all_snapshots() -> Vec<(String, AttributionSnapshot)> {
    STRATEGIES
        .iter()
        .filter_map(|&name| {
            store().snapshot(name).map(|s| (name.to_string(), s))
        })
        .collect()
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn record_and_snapshot() {
        record("direct", AttributionStage::Generated);
        record("direct", AttributionStage::Generated);
        record("direct", AttributionStage::SimPassed);
        record("direct", AttributionStage::Submitted);

        let snap = snapshot("direct").expect("direct strategy should exist");
        assert!(snap.generated >= 2);
        assert!(snap.sim_passed >= 1);
        assert!(snap.submitted >= 1);
    }

    #[test]
    fn submit_and_win_rates() {
        // Use a strategy that's less likely to have been touched by other tests
        record("cow", AttributionStage::Generated);
        record("cow", AttributionStage::Generated);
        record("cow", AttributionStage::Submitted);
        record("cow", AttributionStage::Won);

        let snap = snapshot("cow").unwrap();
        assert!(snap.submit_rate() > 0.0);
        assert!(snap.win_rate() > 0.0);
    }

    #[test]
    fn unknown_strategy_silently_ignored() {
        record("nonexistent_strategy", AttributionStage::Generated);
        assert!(snapshot("nonexistent_strategy").is_none());
    }

    #[test]
    fn all_snapshots_returns_known_strategies() {
        let all = all_snapshots();
        assert!(all.len() >= STRATEGIES.len());
    }

    #[test]
    fn attribution_stage_ordering() {
        assert!(AttributionStage::Generated < AttributionStage::SimPassed);
        assert!(AttributionStage::SimPassed < AttributionStage::Submitted);
        assert!(AttributionStage::Submitted < AttributionStage::Won);
    }
}
